from os import getenv

# Environment variables:
CHROMEDRIVER_PATH = getenv("CHROMEDRIVER_PATH")
METAMASK_EXTENSION_PATH = getenv("METAMASK_EXTENSION_PATH")
SCROLL_PAUSE_TIME = int(getenv("SCROLL_PAUSE_TIME"))
SLEEP_TIME = int(getenv("SLEEP_TIME"))

# Mouse positions:
TRANSFER_BUTTON_POS = (702, 627)
METAMASK_CONTRACT_SCROLL_DOWN_ARROW_POS = (1854, 713)
METAMASK_SCROLL_DOWN_ARROW_POS = (1909, 743)
METAMASK_SIGN_BUTTON_POS = (1784, 697)
